666cbc39ee16
*** Reading local file: /opt/airflow/logs/dag_id=carga_de_locaciones/run_id=manual__2023-05-18T16:16:01.003893+00:00/task_id=obtener_datos/attempt=1.log
[2023-05-18 16:16:06,564] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: carga_de_locaciones.obtener_datos manual__2023-05-18T16:16:01.003893+00:00 [queued]>
[2023-05-18 16:16:06,579] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: carga_de_locaciones.obtener_datos manual__2023-05-18T16:16:01.003893+00:00 [queued]>
[2023-05-18 16:16:06,580] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-05-18 16:16:06,581] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-05-18 16:16:06,582] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-05-18 16:16:06,604] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): obtener_datos> on 2023-05-18 16:16:01.003893+00:00
[2023-05-18 16:16:06,610] {standard_task_runner.py:52} INFO - Started process 318 to run task
[2023-05-18 16:16:06,613] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'carga_de_locaciones', 'obtener_datos', 'manual__2023-05-18T16:16:01.003893+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/dag_carga_automatica_locaciones.py', '--cfg-path', '/tmp/tmpwvqipw_j', '--error-file', '/tmp/tmpdhmagit7']
[2023-05-18 16:16:06,615] {standard_task_runner.py:80} INFO - Job 45: Subtask obtener_datos
[2023-05-18 16:16:06,697] {task_command.py:371} INFO - Running <TaskInstance: carga_de_locaciones.obtener_datos manual__2023-05-18T16:16:01.003893+00:00 [running]> on host 666cbc39ee16
[2023-05-18 16:16:06,805] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=JORGE
AIRFLOW_CTX_DAG_ID=carga_de_locaciones
AIRFLOW_CTX_TASK_ID=obtener_datos
AIRFLOW_CTX_EXECUTION_DATE=2023-05-18T16:16:01.003893+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-18T16:16:01.003893+00:00
[2023-05-18 16:16:12,152] {base.py:68} INFO - Using connection ID 'amazon_redshift' for task execution.
[2023-05-18 16:16:19,036] {python.py:173} INFO - Done. Returned value was: None
[2023-05-18 16:16:19,108] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=carga_de_locaciones, task_id=obtener_datos, execution_date=20230518T161601, start_date=20230518T161606, end_date=20230518T161619
[2023-05-18 16:16:19,205] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-05-18 16:16:19,272] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check

