666cbc39ee16
*** Reading local file: /opt/airflow/logs/dag_id=carga_de_episodios/run_id=manual__2023-05-18T15:50:24.316798+00:00/task_id=obtener_datos/attempt=1.log
[2023-05-18 15:50:29,619] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: carga_de_episodios.obtener_datos manual__2023-05-18T15:50:24.316798+00:00 [queued]>
[2023-05-18 15:50:29,632] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: carga_de_episodios.obtener_datos manual__2023-05-18T15:50:24.316798+00:00 [queued]>
[2023-05-18 15:50:29,633] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-05-18 15:50:29,633] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-05-18 15:50:29,634] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-05-18 15:50:29,657] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): obtener_datos> on 2023-05-18 15:50:24.316798+00:00
[2023-05-18 15:50:29,666] {standard_task_runner.py:52} INFO - Started process 246 to run task
[2023-05-18 15:50:29,672] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'carga_de_episodios', 'obtener_datos', 'manual__2023-05-18T15:50:24.316798+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/dag_carga_automatica_episodios.py', '--cfg-path', '/tmp/tmptvhu8g9s', '--error-file', '/tmp/tmp7ijhd4ji']
[2023-05-18 15:50:29,674] {standard_task_runner.py:80} INFO - Job 42: Subtask obtener_datos
[2023-05-18 15:50:29,747] {task_command.py:371} INFO - Running <TaskInstance: carga_de_episodios.obtener_datos manual__2023-05-18T15:50:24.316798+00:00 [running]> on host 666cbc39ee16
[2023-05-18 15:50:29,862] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=JORGE
AIRFLOW_CTX_DAG_ID=carga_de_episodios
AIRFLOW_CTX_TASK_ID=obtener_datos
AIRFLOW_CTX_EXECUTION_DATE=2023-05-18T15:50:24.316798+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-18T15:50:24.316798+00:00
[2023-05-18 15:50:30,635] {base.py:68} INFO - Using connection ID 'amazon_redshift' for task execution.
[2023-05-18 15:50:37,624] {python.py:173} INFO - Done. Returned value was: None
[2023-05-18 15:50:37,715] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=carga_de_episodios, task_id=obtener_datos, execution_date=20230518T155024, start_date=20230518T155029, end_date=20230518T155037
[2023-05-18 15:50:37,814] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-05-18 15:50:37,848] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check

